language: java
jdk:
 - oraclejdk8
 sudo: enabled
 
services:
- postgresql

script:
    - mvn install
before_install:
  - chmod +x mvnw

services:
- postgresql

before_script:
- psql -c 'CREATE USER root WITH PASSWORD 'root';' -U postgres
- psql -c 'CREATE DATABASE pacientTest;' -U postgres

