language: java
sudo: enabled
jdk:
- oraclejdk8
 
services:
    - postgresql

script:
    - mvn install
    
before_install:
    - chmod +x mvnw

services:
- postgresql

before_script:
    - psql -c 'CREATE DATABASE pacientTest;' -U postgres
    - psql -c 'CREATE USER root WITH PASSWORD 'root';' -U postgres
