language: java
sudo: enabled
jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "samueligt-github"
    token:
    secure: $SONAR_TOKEN
 
services:
    - postgresql

script:
    - mvn install
    - sonar-scanner

    
before_install:
    - chmod +x mvnw

before_script:
  - psql -c 'create database patient;' -U postgres
