language: java
sudo: enabled
jdk:
- oraclejdk8
 
services:
    - postgresql

script:
    - mvn install
    
before_install:
    - chmod +x mvnw

services:
- postgresql

postgres:
  adapter: postgresql
  database: patientTest
  username: root
  password: root

before_script:
    - psql -c 'create database patientTest;' -U postgres
#    - cp config/database.travis.yml config/database.yml
#    - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
    

    
