language: java
sudo: enabled
jdk:
- oraclejdk8
 
services:
    - postgresql

script:
    - mvn install
    
before_install:
    - chmod +x mvnw

services:
- postgresql

before_script:
    - psql -c "CREATE DATABASE patientTest;" -U postgres
    - cp config/database.yml.travis config/database.yml
