language: java
sudo: enabled
jdk:
- oraclejdk8

addons:
    sonarqube:
        organization: samueligt-github
        token:
            secure: $SONAR_TOKEN
        github_token:
            secure: $GITHUB_TOKEN

services:
    - postgresql

script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar-scanner

    
before_install:
    - chmod +x mvnw

before_script:
  - psql -c 'create database patient;' -U postgres
